# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField(help_text='Enter your IITG roll No.')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter event name', max_length=2000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Enter page name', max_length=2000)),
                ('event', models.ManyToManyField(to='iitg.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollNo', models.IntegerField(help_text='Enter your IITG roll No.')),
                ('activeEvent', models.ForeignKey(help_text='a', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='iitg.Event')),
                ('pages', models.ManyToManyField(help_text='Select page(s) which you want to subscribe', to='iitg.Page')),
                ('user', models.OneToOneField(help_text='a', on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='pages',
            field=models.ManyToManyField(help_text='Select page(s) which you want to subscribe', to='iitg.Page'),
        ),
        migrations.AddField(
            model_name='admin',
            name='user',
            field=models.OneToOneField(help_text='a', on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
