# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iitg', '0002_auto_20180929_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='activeEvent',
        ),
    ]
