# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 21:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iitg', '0003_remove_student_activeevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalTime', models.DurationField(help_text='Enter Time required to complete the work')),
                ('description', models.TextField(blank=True, help_text='Enter description', max_length=2000, null=True)),
                ('perDone', models.IntegerField(help_text='Percentage remaining')),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.TextField(help_text='Enter event name', max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pages',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(help_text='Select page(s) which you want to subscribe', related_name='subscribed_pages', to='iitg.Student'),
        ),
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, help_text='Enter description', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='students',
            field=models.ManyToManyField(help_text='Select page(s) which you want to subscribe', related_name='my_pages', to='iitg.Student'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.AddField(
            model_name='page',
            name='deadline',
            field=models.ManyToManyField(help_text='Deadline of the page', to='iitg.Deadline'),
        ),
    ]
