# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-28 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitg', '0004_auto_20180929_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='admins',
            field=models.ManyToManyField(help_text='Select page(s) which you want to subscribe', related_name='my_pages', to='iitg.Student'),
        ),
        migrations.AlterField(
            model_name='page',
            name='students',
            field=models.ManyToManyField(help_text='Select page(s) which you want to subscribe', related_name='subscribed_pages', to='iitg.Student'),
        ),
    ]
