# Generated by Django 2.1.1 on 2018-09-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitg', '0005_auto_20180929_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='deadline',
            field=models.ManyToManyField(blank=True, help_text='Deadline of the page', null=True, to='iitg.Deadline'),
        ),
        migrations.AlterField(
            model_name='page',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='iitg.Event'),
        ),
    ]
