# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-29 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iitg', '0006_auto_20180929_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='key',
            field=models.TextField(blank=True, help_text='Enter page name', max_length=2000, null=True),
        ),
    ]
